service: ai-chatbot
useDotenv: true
frameworkVersion: ^3.12.0

package:
  individually: true
provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-2

plugins:
  # - serverless-plugin-typescript

functions:
  chatbotAgent: ${file(./resources/functions/chatbotAgent.yml)}
