service: ai-chatbot
useDotenv: true
frameworkVersion: ^3.12.0

package:
  individually: true

provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-2
  environment:
    GROQ_API_KEY: ${self:custom.GroqApiKey}

custom:
  esbuild:
    bundle: true
    minify: true
    keepNames: true
    sourcemap: false
    target: node20
    platform: node
    concurrency: 10
    exclude:
      - "@aws-sdk/*"
  AgentMemoryName: ai-chatbot-${sls:stage}-agent-memory
  GroqApiKey: ${file(./resources/secrets/credentials.yml):GroqApiKey}

plugins:
  - serverless-esbuild

resources:
  Resources:
    AgentMemory: ${file(./resources/database/agentMemory.yml)}

functions:
  chatbot: ${file(./resources/functions/chatbot.yml)}
