service: ai-chatbot
useDotenv: true
frameworkVersion: ^3.12.0

package:
  individually: true

provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-2
  environment:
    GROQ_API_KEY: ${self:custom.GroqApiKey}

custom:
  ChatbotAgentMemoryName: ai-chatbot-agent-memory-${sls:stage}
  GroqApiKey: ${file(./resources/secrets/credentials.yml):GroqApiKey}

plugins:
  # - serverless-plugin-typescript

resources:
  Resources:
    ChatbotMemory: ${file(./resources/database/chatbotAgentMemory.yml)}

functions:
  chatbotAgent: ${file(./resources/functions/chatbotAgent.yml)}
